# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfx.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util_pb2 as util__pb2
import devices_pb2 as devices__pb2
import general_pb2 as general__pb2
import groups_pb2 as groups__pb2
import measurements_pb2 as measurements__pb2
import organizations_pb2 as organizations__pb2
import studies_pb2 as studies__pb2
import users_pb2 as users__pb2
import profiles_pb2 as profiles__pb2
import meta_pb2 as meta__pb2
import bundles_pb2 as bundles__pb2

from util_pb2 import *
from devices_pb2 import *
from general_pb2 import *
from groups_pb2 import *
from measurements_pb2 import *
from organizations_pb2 import *
from studies_pb2 import *
from users_pb2 import *
from profiles_pb2 import *
from meta_pb2 import *
from bundles_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='dfx.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\020ai.nuralogix.dfxB\003DFX\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tdfx.proto\x1a\nutil.proto\x1a\rdevices.proto\x1a\rgeneral.proto\x1a\x0cgroups.proto\x1a\x12measurements.proto\x1a\x13organizations.proto\x1a\rstudies.proto\x1a\x0busers.proto\x1a\x0eprofiles.proto\x1a\nmeta.proto\x1a\rbundles.protoB\x1a\n\x10\x61i.nuralogix.dfxB\x03\x44\x46X\xf8\x01\x01P\x00P\x01P\x02P\x03P\x04P\x05P\x06P\x07P\x08P\tP\nb\x06proto3'
  ,
  dependencies=[util__pb2.DESCRIPTOR,devices__pb2.DESCRIPTOR,general__pb2.DESCRIPTOR,groups__pb2.DESCRIPTOR,measurements__pb2.DESCRIPTOR,organizations__pb2.DESCRIPTOR,studies__pb2.DESCRIPTOR,users__pb2.DESCRIPTOR,profiles__pb2.DESCRIPTOR,meta__pb2.DESCRIPTOR,bundles__pb2.DESCRIPTOR,],
  public_dependencies=[util__pb2.DESCRIPTOR,devices__pb2.DESCRIPTOR,general__pb2.DESCRIPTOR,groups__pb2.DESCRIPTOR,measurements__pb2.DESCRIPTOR,organizations__pb2.DESCRIPTOR,studies__pb2.DESCRIPTOR,users__pb2.DESCRIPTOR,profiles__pb2.DESCRIPTOR,meta__pb2.DESCRIPTOR,bundles__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
