# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: util.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='util.proto',
  package='dfx.proto.util',
  syntax='proto3',
  serialized_options=b'\n\020ai.nuralogix.dfxB\004Util\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nutil.proto\x12\x0e\x64\x66x.proto.util\"\xc8\x01\n\x05\x45rror\x12\x0c\n\x04\x43ode\x18\x01 \x01(\t\x12\x31\n\x06\x45rrors\x18\x02 \x03(\x0b\x32!.dfx.proto.util.Error.ErrorsEntry\x12\x0f\n\x07Message\x18\x03 \x01(\t\x1a\x1b\n\x0b\x44\x65scription\x12\x0c\n\x04msgs\x18\x01 \x03(\t\x1aP\n\x0b\x45rrorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.dfx.proto.util.Error.Description:\x02\x38\x01\"\r\n\x0bParamValues\"\r\n\x0bQueryValuesB\x1b\n\x10\x61i.nuralogix.dfxB\x04Util\xf8\x01\x01\x62\x06proto3'
)




_ERROR_DESCRIPTION = _descriptor.Descriptor(
  name='Description',
  full_name='dfx.proto.util.Error.Description',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgs', full_name='dfx.proto.util.Error.Description.msgs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=149,
)

_ERROR_ERRORSENTRY = _descriptor.Descriptor(
  name='ErrorsEntry',
  full_name='dfx.proto.util.Error.ErrorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dfx.proto.util.Error.ErrorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='dfx.proto.util.Error.ErrorsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=231,
)

_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='dfx.proto.util.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='dfx.proto.util.Error.Code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Errors', full_name='dfx.proto.util.Error.Errors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Message', full_name='dfx.proto.util.Error.Message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ERROR_DESCRIPTION, _ERROR_ERRORSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=231,
)


_PARAMVALUES = _descriptor.Descriptor(
  name='ParamValues',
  full_name='dfx.proto.util.ParamValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=246,
)


_QUERYVALUES = _descriptor.Descriptor(
  name='QueryValues',
  full_name='dfx.proto.util.QueryValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=261,
)

_ERROR_DESCRIPTION.containing_type = _ERROR
_ERROR_ERRORSENTRY.fields_by_name['value'].message_type = _ERROR_DESCRIPTION
_ERROR_ERRORSENTRY.containing_type = _ERROR
_ERROR.fields_by_name['Errors'].message_type = _ERROR_ERRORSENTRY
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['ParamValues'] = _PARAMVALUES
DESCRIPTOR.message_types_by_name['QueryValues'] = _QUERYVALUES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {

  'Description' : _reflection.GeneratedProtocolMessageType('Description', (_message.Message,), {
    'DESCRIPTOR' : _ERROR_DESCRIPTION,
    '__module__' : 'util_pb2'
    # @@protoc_insertion_point(class_scope:dfx.proto.util.Error.Description)
    })
  ,

  'ErrorsEntry' : _reflection.GeneratedProtocolMessageType('ErrorsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ERROR_ERRORSENTRY,
    '__module__' : 'util_pb2'
    # @@protoc_insertion_point(class_scope:dfx.proto.util.Error.ErrorsEntry)
    })
  ,
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'util_pb2'
  # @@protoc_insertion_point(class_scope:dfx.proto.util.Error)
  })
_sym_db.RegisterMessage(Error)
_sym_db.RegisterMessage(Error.Description)
_sym_db.RegisterMessage(Error.ErrorsEntry)

ParamValues = _reflection.GeneratedProtocolMessageType('ParamValues', (_message.Message,), {
  'DESCRIPTOR' : _PARAMVALUES,
  '__module__' : 'util_pb2'
  # @@protoc_insertion_point(class_scope:dfx.proto.util.ParamValues)
  })
_sym_db.RegisterMessage(ParamValues)

QueryValues = _reflection.GeneratedProtocolMessageType('QueryValues', (_message.Message,), {
  'DESCRIPTOR' : _QUERYVALUES,
  '__module__' : 'util_pb2'
  # @@protoc_insertion_point(class_scope:dfx.proto.util.QueryValues)
  })
_sym_db.RegisterMessage(QueryValues)


DESCRIPTOR._options = None
_ERROR_ERRORSENTRY._options = None
# @@protoc_insertion_point(module_scope)
